### ISSUE TITLE
Invalid Wire-type 7  Editor 5.0.  PS3 save.

### ISSUE THREAD

**Issue by dfdalamar** [Tonic-Box/D3RoSEdit#1]
When I try to load the save from my PS3 I get an unhandled exception.  Error details.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid wire-type: 7
Parameter name: wireType
   at D3.Application.FrmMain.backgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\zacke\Desktop\MyTools\D3Edit Source - Copy\XPosedDIIIEditor\FrmMain.cs:line 494
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
D3 RoS Edit - v5.0
    Assembly Version: 1.233.21.0
    Win32 Version: 1.0
    CodeBase: file:///C:/D3.RoS.Edit.-.v5.0/D3%20RoS%20Edit%20-%20v5.0.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
D3.Ui
    Assembly Version: 10.4.22.0
    Win32 Version: 1.0
    CodeBase: file:///C:/D3.RoS.Edit.-.v5.0/bin/dll/D3.Ui.DLL
----------------------------------------
D3.GameInfo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/D3.RoS.Edit.-.v5.0/bin/dll/D3.GameInfo.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
D3.Protobuf
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/D3.RoS.Edit.-.v5.0/bin/dll/D3.Protobuf.DLL
----------------------------------------
protobuf-net
    Assembly Version: 2.0.0.668
    Win32 Version: 2.0.0.668
    CodeBase: file:///C:/D3.RoS.Edit.-.v5.0/bin/dll/protobuf-net.DLL
----------------------------------------
Ionic.Zip
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///C:/D3.RoS.Edit.-.v5.0/bin/dll/Ionic.Zip.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Tonic-Box** [comment]
You need to first decrypt your ps3 save.

**Comment by dfdalamar** [comment]
I feel stupid.  It has been a few months since I edited.  Thanks.

**Comment by Tonic-Box** [comment]
Nah youre good, happens to us all haha. Glad you got it sorted!
